### ISSUE TITLE
Migrations not distributed in package

### ISSUE THREAD

**Issue by dfrankow** [vishalanandl177/DRF-API-Logger#6]
Thanks for this package. I'm excited to try it.

When I got it, it needed a migration, but that migration isn't saved in the package.

```
$ ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, ..., sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

$ ./manage.py makemigrations
Migrations for 'drf_api_logger':
  .venv/lib/python3.9/site-packages/drf_api_logger/migrations/0001_initial.py
    - Create model APILogsModel
```

I believe you should make the migration and check it in.

I could probably produce a pull request if you wish.

**Comment by 3lf** [comment]
i have same issue

**Comment by dfrankow** [comment]
Accepting #7 fixes this

**Comment by dfrankow** [comment]
#7 was merged, so I think this is fixed.

**Comment by 3lf** [comment]
![Screenshot from 2021-03-10 15-54-21](https://user-images.githubusercontent.com/25196606/110629091-0bb0c880-81b9-11eb-8dd8-60b3d5814690.png)
This error still exists

**Comment by dfrankow** [comment]
What version do you have installed?

Also, can you run showmigrations and paste the output?
